# generated_by: flow_studio
from pathlib import Path

from ffengine.airflow.generated_factory import build_generated_dag

CONFIG_PATH = Path("/opt/airflow/projects/webhook/oc_epr/main/main/webhook_oc_epr_main_main_group_1.yaml")
DAG_ID = "webhook_oc_epr_main_main_group_1_dag"
DAG_TAGS = ["webhook", "oc_epr", "main"]
UPSTREAM_DAG_IDS = []
RAW_CONFIG = {'source_db_var': 'dwh_webhook',
 'target_db_var': 'dwh_webhook',
 'flow_tasks': [{'task_type': 'dag',
                 'task_group_id': '1_dwh_webhook_dag_webhook_oc_epr_level1_source_to_stg_group_3_dag_to_dwh_webhook_dag_tgt_table',
                 'depends_on': [],
                 'source_schema': '',
                 'source_table': '',
                 'source_type': 'table',
                 'inline_sql': None,
                 'script_run_environment': None,
                 'script_sql': None,
                 'dag_task_dag_id': 'webhook_oc_epr_level1_source_to_stg_group_3_dag',
                 'column_mapping_mode': 'source',
                 'target_schema': 'script_tgt',
                 'target_table': 'script_task',
                 'load_method': 'create_if_not_exists_or_truncate',
                 'where': None,
                 'batch_size': 10000,
                 'partitioning': {'enabled': False,
                                  'mode': 'auto_numeric',
                                  'column': None,
                                  'parts': 2,
                                  'distinct_limit': 16,
                                  'ranges': []},
                 'tags': ['webhook', 'oc_epr', 'main']},
                {'task_type': 'dag',
                 'task_group_id': '2_dwh_webhook_dag_webhook_oc_epr_level2_stg_to_ocepr_group_2_dag_to_dwh_webhook_dag_tgt_table',
                 'depends_on': ['1_dwh_webhook_dag_webhook_oc_epr_level1_source_to_stg_group_3_dag_to_dwh_webhook_dag_tgt_table'],
                 'source_schema': '',
                 'source_table': '',
                 'source_type': 'table',
                 'inline_sql': None,
                 'script_run_environment': None,
                 'script_sql': None,
                 'dag_task_dag_id': 'webhook_oc_epr_level2_stg_to_ocepr_group_2_dag',
                 'column_mapping_mode': 'source',
                 'target_schema': 'script_tgt',
                 'target_table': 'script_task',
                 'load_method': 'create_if_not_exists_or_truncate',
                 'where': None,
                 'batch_size': 10000,
                 'partitioning': {'enabled': False,
                                  'mode': 'auto_numeric',
                                  'column': None,
                                  'parts': 2,
                                  'distinct_limit': 16,
                                  'ranges': []},
                 'tags': ['webhook', 'oc_epr', 'main']}],
 'custom_tags': ['main'],
 'scheduler': {'cron_expression': '16 * * * *',
               'timezone': 'Europe/Istanbul',
               'active': True,
               'start_date': '2026-05-01T19:12:00'},
 'dag_dependencies': {'upstream_dag_ids': []},
 '__config_path': '/opt/airflow/projects/webhook/oc_epr/main/main/webhook_oc_epr_main_main_group_1.yaml'}

dag = build_generated_dag(
    dag_id=DAG_ID,
    dag_tags=DAG_TAGS,
    upstream_dag_ids=UPSTREAM_DAG_IDS,
    raw_config_snapshot=RAW_CONFIG,
)
