source_db_var: dwh_webhook
target_db_var: dwh_webhook
flow_tasks:
- task_type: script_run
  task_group_id: 1_dwh_webhook_script_target_to_dwh_webhook_script_tgt_table
  depends_on: []
  source_schema: ''
  source_table: ''
  source_type: sql
  inline_sql: null
  script_run_environment: target
  script_sql: delete from "WHK"."TRANSMISSIONS" where "SYSTEM_ENTRY_DATE_TIME" >=
    :stg_min_system_entry_date_time
  dag_task_dag_id: null
  column_mapping_mode: mapping_file
  target_schema: script_tgt
  target_table: script_task
  load_method: create_if_not_exists_or_truncate
  where: null
  batch_size: 10000
  partitioning:
    enabled: false
    mode: auto_numeric
    column: null
    parts: 2
    distinct_limit: 16
    ranges: []
  tags: &id001
  - webhook
  - whk
  - level2
  - stg_to_whk
  bindings:
  - variable_name: stg_min_system_entry_date_time
    binding_source: target
    default_value: null
    sql: "SELECT min(\"SYSTEM_ENTRY_DATE_TIME\") \nFROM  dwh_stg.\"TRANSMISSIONS\""
    airflow_variable_key: null
- task_type: source_target
  task_group_id: 2_dwh_webhook_dwh_stg_transmissions_to_dwh_webhook_append_whk_transmissions
  depends_on: []
  source_schema: dwh_stg
  source_table: TRANSMISSIONS
  source_type: table
  inline_sql: null
  script_run_environment: null
  script_sql: null
  dag_task_dag_id: null
  column_mapping_mode: source
  target_schema: WHK
  target_table: TRANSMISSIONS
  load_method: append
  where: null
  batch_size: 10000
  partitioning:
    enabled: false
    mode: auto_numeric
    column: null
    parts: 2
    distinct_limit: 16
    ranges: []
  tags: *id001
custom_tags: []
scheduler:
  cron_expression: null
  timezone: Europe/Istanbul
  active: true
  start_date: '2026-05-01T18:33:28'
dag_dependencies:
  upstream_dag_ids: []
